/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cphvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public cphvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(cphvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_cphvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public cphvector() {
    this(libnfdbJNI.new_cphvector__SWIG_0(), true);
  }

  public cphvector(long n) {
    this(libnfdbJNI.new_cphvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.cphvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.cphvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.cphvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.cphvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.cphvector_clear(swigCPtr, this);
  }

  public void add(ContentPlaceholder x) {
    libnfdbJNI.cphvector_add(swigCPtr, this, ContentPlaceholder.getCPtr(x), x);
  }

  public ContentPlaceholder get(int i) {
    return new ContentPlaceholder(libnfdbJNI.cphvector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ContentPlaceholder val) {
    libnfdbJNI.cphvector_set(swigCPtr, this, i, ContentPlaceholder.getCPtr(val), val);
  }

}
