/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Feed {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Feed(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Feed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Feed(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Feed_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Feed_id_get(swigCPtr, this);
  }

  public void setUrl(String value) {
    libnfdbJNI.Feed_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return libnfdbJNI.Feed_url_get(swigCPtr, this);
  }

  public void setName(String value) {
    libnfdbJNI.Feed_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libnfdbJNI.Feed_name_get(swigCPtr, this);
  }

  public void setFrequency(int value) {
    libnfdbJNI.Feed_frequency_set(swigCPtr, this, value);
  }

  public int getFrequency() {
    return libnfdbJNI.Feed_frequency_get(swigCPtr, this);
  }

  public void setLastUpdate(DateTime value) {
    libnfdbJNI.Feed_lastUpdate_set(swigCPtr, this, DateTime.getCPtr(value), value);
  }

  public DateTime getLastUpdate() {
    long cPtr = libnfdbJNI.Feed_lastUpdate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DateTime(cPtr, false);
  }

  public void setCategory(SWIGTYPE_p_std__string value) {
    libnfdbJNI.Feed_category_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getCategory() {
    long cPtr = libnfdbJNI.Feed_category_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setType(SWIGTYPE_p_int value) {
    libnfdbJNI.Feed_type_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getType() {
    long cPtr = libnfdbJNI.Feed_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setFavIcon(String value) {
    libnfdbJNI.Feed_favIcon_set(swigCPtr, this, value);
  }

  public String getFavIcon() {
    return libnfdbJNI.Feed_favIcon_get(swigCPtr, this);
  }

  public void setIconSize(int value) {
    libnfdbJNI.Feed_iconSize_set(swigCPtr, this, value);
  }

  public int getIconSize() {
    return libnfdbJNI.Feed_iconSize_get(swigCPtr, this);
  }

  public Feed() {
    this(libnfdbJNI.new_Feed__SWIG_0(), true);
  }

  public Feed(int id, String url, String name, int frequency, DateTime lastUpdate, SWIGTYPE_p_std__string category, SWIGTYPE_p_int type, String favIcon, int iconSize) {
    this(libnfdbJNI.new_Feed__SWIG_1(id, url, name, frequency, DateTime.getCPtr(lastUpdate), lastUpdate, SWIGTYPE_p_std__string.getCPtr(category), SWIGTYPE_p_int.getCPtr(type), favIcon, iconSize), true);
  }

  public void Destroy() {
    libnfdbJNI.Feed_Destroy(swigCPtr, this);
  }

}
