/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GroupPlaceholder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GroupPlaceholder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GroupPlaceholder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_GroupPlaceholder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.GroupPlaceholder_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.GroupPlaceholder_id_get(swigCPtr, this);
  }

  public GroupPlaceholder() {
    this(libnfdbJNI.new_GroupPlaceholder__SWIG_0(), true);
  }

  public GroupPlaceholder(int id) {
    this(libnfdbJNI.new_GroupPlaceholder__SWIG_1(id), true);
  }

  public void Destroy() {
    libnfdbJNI.GroupPlaceholder_Destroy(swigCPtr, this);
  }

}
