/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Item {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Item(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Item obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Item(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Item_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Item_id_get(swigCPtr, this);
  }

  public void setFeedId(int value) {
    libnfdbJNI.Item_feedId_set(swigCPtr, this, value);
  }

  public int getFeedId() {
    return libnfdbJNI.Item_feedId_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    libnfdbJNI.Item_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return libnfdbJNI.Item_title_get(swigCPtr, this);
  }

  public void setUrl(String value) {
    libnfdbJNI.Item_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return libnfdbJNI.Item_url_get(swigCPtr, this);
  }

  public void setContent(String value) {
    libnfdbJNI.Item_content_set(swigCPtr, this, value);
  }

  public String getContent() {
    return libnfdbJNI.Item_content_get(swigCPtr, this);
  }

  public void setPostDate(DateTime value) {
    libnfdbJNI.Item_postDate_set(swigCPtr, this, DateTime.getCPtr(value), value);
  }

  public DateTime getPostDate() {
    long cPtr = libnfdbJNI.Item_postDate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DateTime(cPtr, false);
  }

  public void setAuthor(SWIGTYPE_p_std__string value) {
    libnfdbJNI.Item_author_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getAuthor() {
    long cPtr = libnfdbJNI.Item_author_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setGeolocation(SWIGTYPE_p_std__string value) {
    libnfdbJNI.Item_geolocation_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGeolocation() {
    long cPtr = libnfdbJNI.Item_geolocation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public Item() {
    this(libnfdbJNI.new_Item__SWIG_0(), true);
  }

  public Item(int id, int feedId, String title, String url, String content, DateTime postDate, SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string geolocation) {
    this(libnfdbJNI.new_Item__SWIG_1(id, feedId, title, url, content, DateTime.getCPtr(postDate), postDate, SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(geolocation)), true);
  }

  public void Destroy() {
    libnfdbJNI.Item_Destroy(swigCPtr, this);
  }

}
