/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ItemController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ItemController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ItemController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_ItemController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ItemController() {
    this(libnfdbJNI.new_ItemController(), true);
  }

  public Item GetItemById(int id) {
    long cPtr = libnfdbJNI.ItemController_GetItemById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Item(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__Item_p_t GetItemsByFeedId(int feedId) {
    return new SWIGTYPE_p_std__vectorT_nfdb__Item_p_t(libnfdbJNI.ItemController_GetItemsByFeedId(swigCPtr, this, feedId), true);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__Item_p_t GetAllItems() {
    return new SWIGTYPE_p_std__vectorT_nfdb__Item_p_t(libnfdbJNI.ItemController_GetAllItems(swigCPtr, this), true);
  }

  public int AddItem(Item item) {
    return libnfdbJNI.ItemController_AddItem(swigCPtr, this, Item.getCPtr(item), item);
  }

  public void UpdateItem(Item item) {
    libnfdbJNI.ItemController_UpdateItem__SWIG_0(swigCPtr, this, Item.getCPtr(item), item);
  }

  public void UpdateItem(int id, SWIGTYPE_p_int feedId, SWIGTYPE_p_std__string title, SWIGTYPE_p_std__string url, SWIGTYPE_p_std__string content, DateTime postDate, SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string geolocation) {
    libnfdbJNI.ItemController_UpdateItem__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_int.getCPtr(feedId), SWIGTYPE_p_std__string.getCPtr(title), SWIGTYPE_p_std__string.getCPtr(url), SWIGTYPE_p_std__string.getCPtr(content), DateTime.getCPtr(postDate), postDate, SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(geolocation));
  }

  public void RemoveItem(int id) {
    libnfdbJNI.ItemController_RemoveItem(swigCPtr, this, id);
  }

  public Item GenerateItem(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.ItemController_GenerateItem(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Item(cPtr, false);
  }

}
