/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class itemvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public itemvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(itemvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_itemvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public itemvector() {
    this(libnfdbJNI.new_itemvector__SWIG_0(), true);
  }

  public itemvector(long n) {
    this(libnfdbJNI.new_itemvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.itemvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.itemvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.itemvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.itemvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.itemvector_clear(swigCPtr, this);
  }

  public void add(Item x) {
    libnfdbJNI.itemvector_add(swigCPtr, this, Item.getCPtr(x), x);
  }

  public Item get(int i) {
    return new Item(libnfdbJNI.itemvector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Item val) {
    libnfdbJNI.itemvector_set(swigCPtr, this, i, Item.getCPtr(val), val);
  }

}
