/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class LayoutController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LayoutController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LayoutController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_LayoutController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LayoutController() {
    this(libnfdbJNI.new_LayoutController(), true);
  }

  public Layout GetLayoutById(int id) {
    return new Layout(libnfdbJNI.LayoutController_GetLayoutById(swigCPtr, this, id), true);
  }

  public layoutvector GetAllLayouts() {
    return new layoutvector(libnfdbJNI.LayoutController_GetAllLayouts(swigCPtr, this), true);
  }

  public void AddLayout(Layout layout) {
    libnfdbJNI.LayoutController_AddLayout(swigCPtr, this, Layout.getCPtr(layout), layout);
  }

  public void UpdateLayout(Layout layout) {
    libnfdbJNI.LayoutController_UpdateLayout(swigCPtr, this, Layout.getCPtr(layout), layout);
  }

  public void RemoveLayout(Layout layout) {
    libnfdbJNI.LayoutController_RemoveLayout(swigCPtr, this, Layout.getCPtr(layout), layout);
  }

  public Layout GenerateLayout(SWIGTYPE_p_sql__ResultSet rs) {
    return new Layout(libnfdbJNI.LayoutController_GenerateLayout(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs)), true);
  }

}
