/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Notification {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Notification(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Notification obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Notification(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Notification_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Notification_id_get(swigCPtr, this);
  }

  public void setUsername(String value) {
    libnfdbJNI.Notification_username_set(swigCPtr, this, value);
  }

  public String getUsername() {
    return libnfdbJNI.Notification_username_get(swigCPtr, this);
  }

  public void setSheetId(int value) {
    libnfdbJNI.Notification_sheetId_set(swigCPtr, this, value);
  }

  public int getSheetId() {
    return libnfdbJNI.Notification_sheetId_get(swigCPtr, this);
  }

  public Notification() {
    this(libnfdbJNI.new_Notification__SWIG_0(), true);
  }

  public Notification(int id, String username, int sheetId) {
    this(libnfdbJNI.new_Notification__SWIG_1(id, username, sheetId), true);
  }

  public void Destroy() {
    libnfdbJNI.Notification_Destroy(swigCPtr, this);
  }

}
