/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Session {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Session(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Session obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Session(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Session_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Session_id_get(swigCPtr, this);
  }

  public void setUsername(String value) {
    libnfdbJNI.Session_username_set(swigCPtr, this, value);
  }

  public String getUsername() {
    return libnfdbJNI.Session_username_get(swigCPtr, this);
  }

  public void setKey(String value) {
    libnfdbJNI.Session_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return libnfdbJNI.Session_key_get(swigCPtr, this);
  }

  public void setTime(DateTime value) {
    libnfdbJNI.Session_time_set(swigCPtr, this, DateTime.getCPtr(value), value);
  }

  public DateTime getTime() {
    long cPtr = libnfdbJNI.Session_time_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DateTime(cPtr, false);
  }

  public Session() {
    this(libnfdbJNI.new_Session__SWIG_0(), true);
  }

  public Session(int id, String username, String key, DateTime time) {
    this(libnfdbJNI.new_Session__SWIG_1(id, username, key, DateTime.getCPtr(time), time), true);
  }

  public void Destroy() {
    libnfdbJNI.Session_Destroy(swigCPtr, this);
  }

}
