/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sessionvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public sessionvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(sessionvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_sessionvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sessionvector() {
    this(libnfdbJNI.new_sessionvector__SWIG_0(), true);
  }

  public sessionvector(long n) {
    this(libnfdbJNI.new_sessionvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.sessionvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.sessionvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.sessionvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.sessionvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.sessionvector_clear(swigCPtr, this);
  }

  public void add(Session x) {
    libnfdbJNI.sessionvector_add(swigCPtr, this, Session.getCPtr(x), x);
  }

  public Session get(int i) {
    return new Session(libnfdbJNI.sessionvector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Session val) {
    libnfdbJNI.sessionvector_set(swigCPtr, this, i, Session.getCPtr(val), val);
  }

}
