/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SessionController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SessionController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SessionController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_SessionController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SessionController() {
    this(libnfdbJNI.new_SessionController(), true);
  }

  public Session GetSessionById(int id) {
    long cPtr = libnfdbJNI.SessionController_GetSessionById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__Session_p_t GetSessionsByUsername(String username) {
    return new SWIGTYPE_p_std__vectorT_nfdb__Session_p_t(libnfdbJNI.SessionController_GetSessionsByUsername(swigCPtr, this, username), true);
  }

  public Session GetSessionByKey(String key) {
    long cPtr = libnfdbJNI.SessionController_GetSessionByKey(swigCPtr, this, key);
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__Session_p_t GetAllSessions() {
    return new SWIGTYPE_p_std__vectorT_nfdb__Session_p_t(libnfdbJNI.SessionController_GetAllSessions(swigCPtr, this), true);
  }

  public int AddSession(Session session) {
    return libnfdbJNI.SessionController_AddSession(swigCPtr, this, Session.getCPtr(session), session);
  }

  public void UpdateSession(Session session) {
    libnfdbJNI.SessionController_UpdateSession__SWIG_0(swigCPtr, this, Session.getCPtr(session), session);
  }

  public void UpdateSession(int id, SWIGTYPE_p_std__string username, SWIGTYPE_p_std__string key, DateTime time) {
    libnfdbJNI.SessionController_UpdateSession__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_std__string.getCPtr(username), SWIGTYPE_p_std__string.getCPtr(key), DateTime.getCPtr(time), time);
  }

  public void RemoveSession(int id) {
    libnfdbJNI.SessionController_RemoveSession(swigCPtr, this, id);
  }

  public Session GenerateSession(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.SessionController_GenerateSession(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

}
