/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Sheet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Sheet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Sheet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Sheet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Sheet_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Sheet_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    libnfdbJNI.Sheet_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libnfdbJNI.Sheet_name_get(swigCPtr, this);
  }

  public void setUsername(String value) {
    libnfdbJNI.Sheet_username_set(swigCPtr, this, value);
  }

  public String getUsername() {
    return libnfdbJNI.Sheet_username_get(swigCPtr, this);
  }

  public void setUpdated(DateTime value) {
    libnfdbJNI.Sheet_updated_set(swigCPtr, this, DateTime.getCPtr(value), value);
  }

  public DateTime getUpdated() {
    long cPtr = libnfdbJNI.Sheet_updated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DateTime(cPtr, false);
  }

  public void setLayoutId(int value) {
    libnfdbJNI.Sheet_layoutId_set(swigCPtr, this, value);
  }

  public int getLayoutId() {
    return libnfdbJNI.Sheet_layoutId_get(swigCPtr, this);
  }

  public Sheet() {
    this(libnfdbJNI.new_Sheet__SWIG_0(), true);
  }

  public Sheet(int id, String name, String username, DateTime updated, int layoutId) {
    this(libnfdbJNI.new_Sheet__SWIG_1(id, name, username, DateTime.getCPtr(updated), updated, layoutId), true);
  }

  public void Destroy() {
    libnfdbJNI.Sheet_Destroy(swigCPtr, this);
  }

}
