/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sheetvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public sheetvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(sheetvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_sheetvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sheetvector() {
    this(libnfdbJNI.new_sheetvector__SWIG_0(), true);
  }

  public sheetvector(long n) {
    this(libnfdbJNI.new_sheetvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.sheetvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.sheetvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.sheetvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.sheetvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.sheetvector_clear(swigCPtr, this);
  }

  public void add(Sheet x) {
    libnfdbJNI.sheetvector_add(swigCPtr, this, Sheet.getCPtr(x), x);
  }

  public Sheet get(int i) {
    return new Sheet(libnfdbJNI.sheetvector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Sheet val) {
    libnfdbJNI.sheetvector_set(swigCPtr, this, i, Sheet.getCPtr(val), val);
  }

}
