/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Stat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Stat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Stat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Stat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Stat_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Stat_id_get(swigCPtr, this);
  }

  public void setUsers(int value) {
    libnfdbJNI.Stat_users_set(swigCPtr, this, value);
  }

  public int getUsers() {
    return libnfdbJNI.Stat_users_get(swigCPtr, this);
  }

  public void setSheets(int value) {
    libnfdbJNI.Stat_sheets_set(swigCPtr, this, value);
  }

  public int getSheets() {
    return libnfdbJNI.Stat_sheets_get(swigCPtr, this);
  }

  public void setFeeds(int value) {
    libnfdbJNI.Stat_feeds_set(swigCPtr, this, value);
  }

  public int getFeeds() {
    return libnfdbJNI.Stat_feeds_get(swigCPtr, this);
  }

  public void setItems(int value) {
    libnfdbJNI.Stat_items_set(swigCPtr, this, value);
  }

  public int getItems() {
    return libnfdbJNI.Stat_items_get(swigCPtr, this);
  }

  public void setComments(int value) {
    libnfdbJNI.Stat_comments_set(swigCPtr, this, value);
  }

  public int getComments() {
    return libnfdbJNI.Stat_comments_get(swigCPtr, this);
  }

  public Stat() {
    this(libnfdbJNI.new_Stat__SWIG_0(), true);
  }

  public Stat(int id, int users, int sheets, int feeds, int items, int comments) {
    this(libnfdbJNI.new_Stat__SWIG_1(id, users, sheets, feeds, items, comments), true);
  }

  public void Destroy() {
    libnfdbJNI.Stat_Destroy(swigCPtr, this);
  }

}
