/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class StatController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public StatController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StatController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_StatController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StatController() {
    this(libnfdbJNI.new_StatController(), true);
  }

  public Stat GetStatById(int id) {
    long cPtr = libnfdbJNI.StatController_GetStatById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Stat(cPtr, false);
  }

  public Stat GetLatestStat() {
    long cPtr = libnfdbJNI.StatController_GetLatestStat(swigCPtr, this);
    return (cPtr == 0) ? null : new Stat(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__Stat_p_t GetAllStats() {
    return new SWIGTYPE_p_std__vectorT_nfdb__Stat_p_t(libnfdbJNI.StatController_GetAllStats(swigCPtr, this), true);
  }

  public int AddStat(Stat stat) {
    return libnfdbJNI.StatController_AddStat(swigCPtr, this, Stat.getCPtr(stat), stat);
  }

  public void UpdateStat(Stat stat) {
    libnfdbJNI.StatController_UpdateStat__SWIG_0(swigCPtr, this, Stat.getCPtr(stat), stat);
  }

  public void UpdateStat(int id, SWIGTYPE_p_int users, SWIGTYPE_p_int sheets, SWIGTYPE_p_int feeds, SWIGTYPE_p_int items, SWIGTYPE_p_int comments) {
    libnfdbJNI.StatController_UpdateStat__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_int.getCPtr(users), SWIGTYPE_p_int.getCPtr(sheets), SWIGTYPE_p_int.getCPtr(feeds), SWIGTYPE_p_int.getCPtr(items), SWIGTYPE_p_int.getCPtr(comments));
  }

  public void RemoveStat(int id) {
    libnfdbJNI.StatController_RemoveStat(swigCPtr, this, id);
  }

  public Stat GenerateStat(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.StatController_GenerateStat(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Stat(cPtr, false);
  }

}
