/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DBFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_DBFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static IFeedController GetFeedController() {
    long cPtr = libnfdbJNI.DBFactory_GetFeedController();
    return (cPtr == 0) ? null : new IFeedController(cPtr, false);
  }

  public static ISheetController GetSheetController() {
    long cPtr = libnfdbJNI.DBFactory_GetSheetController();
    return (cPtr == 0) ? null : new ISheetController(cPtr, false);
  }

  public static IUserController GetUserController() {
    long cPtr = libnfdbJNI.DBFactory_GetUserController();
    return (cPtr == 0) ? null : new IUserController(cPtr, false);
  }

  public DBFactory() {
    this(libnfdbJNI.new_DBFactory(), true);
  }

}
