/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IFeedController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IFeedController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IFeedController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_IFeedController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Feed GetFeedById(int id) {
    return new Feed(libnfdbJNI.IFeedController_GetFeedById(swigCPtr, this, id), true);
  }

  public void UpdateFeed(Feed feed) {
    libnfdbJNI.IFeedController_UpdateFeed(swigCPtr, this, Feed.getCPtr(feed), feed);
  }

  public void AddFeed(Feed feed) {
    libnfdbJNI.IFeedController_AddFeed(swigCPtr, this, Feed.getCPtr(feed), feed);
  }

}
