/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ISheetController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ISheetController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ISheetController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_ISheetController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Sheet GetSheetById(int id) {
    return new Sheet(libnfdbJNI.ISheetController_GetSheetById(swigCPtr, this, id), true);
  }

  public void UpdateSheet(Sheet sheet) {
    libnfdbJNI.ISheetController_UpdateSheet(swigCPtr, this, Sheet.getCPtr(sheet), sheet);
  }

  public void AddSheet(Sheet sheet) {
    libnfdbJNI.ISheetController_AddSheet(swigCPtr, this, Sheet.getCPtr(sheet), sheet);
  }

}
