/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class libnfdbJNI {
  public final static native long new_DateTime__SWIG_0();
  public final static native long new_DateTime__SWIG_1(long jarg1, DateTime jarg1_);
  public final static native void delete_DateTime(long jarg1);
  public final static native long DateTime_ExportToMySQL(long jarg1, DateTime jarg1_);
  public final static native void DateTime_ImportFromMySQL(long jarg1, DateTime jarg1_, long jarg2);
  public final static native void DateTime_ParseFromString(long jarg1, DateTime jarg1_, String jarg2);
  public final static native int DateTime_GetSecond(long jarg1, DateTime jarg1_);
  public final static native int DateTime_GetMinute(long jarg1, DateTime jarg1_);
  public final static native int DateTime_GetHour(long jarg1, DateTime jarg1_);
  public final static native int DateTime_GetDay(long jarg1, DateTime jarg1_);
  public final static native int DateTime_GetMonth(long jarg1, DateTime jarg1_);
  public final static native int DateTime_GetYear(long jarg1, DateTime jarg1_);
  public final static native void DateTime_SetSecond(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetMinute(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetHour(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetDay(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetMonth(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetYear(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_Set(long jarg1, DateTime jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);
  public final static native void DateTime_SetTimeOffset__SWIG_0(long jarg1, DateTime jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native void DateTime_SetTimeOffset__SWIG_1(long jarg1, DateTime jarg1_, int jarg2, int jarg3);
  public final static native void DateTime_SetTimeOffset__SWIG_2(long jarg1, DateTime jarg1_, int jarg2);
  public final static native void DateTime_SetDateOffset__SWIG_0(long jarg1, DateTime jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native void DateTime_SetDateOffset__SWIG_1(long jarg1, DateTime jarg1_, int jarg2, int jarg3);
  public final static native void DateTime_SetDateOffset__SWIG_2(long jarg1, DateTime jarg1_, int jarg2);
  public final static native long new_User();
  public final static native void delete_User(long jarg1);
  public final static native long new_Sheet();
  public final static native void delete_Sheet(long jarg1);
  public final static native long new_Feed();
  public final static native void delete_Feed(long jarg1);
  public final static native long ISheetController_GetSheetById(long jarg1, ISheetController jarg1_, int jarg2);
  public final static native void ISheetController_UpdateSheet(long jarg1, ISheetController jarg1_, long jarg2, Sheet jarg2_);
  public final static native void ISheetController_AddSheet(long jarg1, ISheetController jarg1_, long jarg2, Sheet jarg2_);
  public final static native void delete_ISheetController(long jarg1);
  public final static native long IUserController_GetUserById(long jarg1, IUserController jarg1_, int jarg2);
  public final static native long IUserController_GetUserByUsername(long jarg1, IUserController jarg1_, long jarg2);
  public final static native void IUserController_UpdateUser(long jarg1, IUserController jarg1_, long jarg2, User jarg2_);
  public final static native void IUserController_AddUser(long jarg1, IUserController jarg1_, long jarg2, User jarg2_);
  public final static native void delete_IUserController(long jarg1);
  public final static native long IFeedController_GetFeedById(long jarg1, IFeedController jarg1_, int jarg2);
  public final static native void IFeedController_UpdateFeed(long jarg1, IFeedController jarg1_, long jarg2, Feed jarg2_);
  public final static native void IFeedController_AddFeed(long jarg1, IFeedController jarg1_, long jarg2, Feed jarg2_);
  public final static native void delete_IFeedController(long jarg1);
  public final static native long DBFactory_GetFeedController();
  public final static native long DBFactory_GetSheetController();
  public final static native long DBFactory_GetUserController();
  public final static native long new_DBFactory();
  public final static native void delete_DBFactory(long jarg1);
}
