/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class commentvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected commentvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(commentvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_commentvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public commentvector() {
    this(libnfdbJNI.new_commentvector__SWIG_0(), true);
  }

  public commentvector(long n) {
    this(libnfdbJNI.new_commentvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.commentvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.commentvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.commentvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.commentvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.commentvector_clear(swigCPtr, this);
  }

  public void add(Comment x) {
    libnfdbJNI.commentvector_add(swigCPtr, this, Comment.getCPtr(x), x);
  }

  public Comment get(int i) {
    long cPtr = libnfdbJNI.commentvector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

  public void set(int i, Comment val) {
    libnfdbJNI.commentvector_set(swigCPtr, this, i, Comment.getCPtr(val), val);
  }

}
