/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class CommentController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CommentController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommentController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_CommentController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CommentController() {
    this(libnfdbJNI.new_CommentController(), true);
  }

  public Comment GetCommentById(int id) {
    long cPtr = libnfdbJNI.CommentController_GetCommentById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

  public commentvector GetCommentsByItemId(int itemId) {
    return new commentvector(libnfdbJNI.CommentController_GetCommentsByItemId(swigCPtr, this, itemId), true);
  }

  public commentvector GetAllComments() {
    return new commentvector(libnfdbJNI.CommentController_GetAllComments(swigCPtr, this), true);
  }

  public int AddComment(Comment comment) {
    return libnfdbJNI.CommentController_AddComment(swigCPtr, this, Comment.getCPtr(comment), comment);
  }

  public void UpdateComment(Comment comment) {
    libnfdbJNI.CommentController_UpdateComment__SWIG_0(swigCPtr, this, Comment.getCPtr(comment), comment);
  }

  public void UpdateComment(int id, SWIGTYPE_p_int itemId, SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string via, DateTime date, SWIGTYPE_p_std__string comment, String avatar, int avatarSize) {
    libnfdbJNI.CommentController_UpdateComment__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_int.getCPtr(itemId), SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(via), DateTime.getCPtr(date), date, SWIGTYPE_p_std__string.getCPtr(comment), avatar, avatarSize);
  }

  public void RemoveComment(int id) {
    libnfdbJNI.CommentController_RemoveComment(swigCPtr, this, id);
  }

  public Comment GenerateComment(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.CommentController_GenerateComment(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

}
