/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class Comment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Comment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Comment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Comment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Comment_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Comment_id_get(swigCPtr, this);
  }

  public void setItemId(int value) {
    libnfdbJNI.Comment_itemId_set(swigCPtr, this, value);
  }

  public int getItemId() {
    return libnfdbJNI.Comment_itemId_get(swigCPtr, this);
  }

  public void setAuthor(String value) {
    libnfdbJNI.Comment_author_set(swigCPtr, this, value);
  }

  public String getAuthor() {
    return libnfdbJNI.Comment_author_get(swigCPtr, this);
  }

  public void setVia(String value) {
    libnfdbJNI.Comment_via_set(swigCPtr, this, value);
  }

  public String getVia() {
    return libnfdbJNI.Comment_via_get(swigCPtr, this);
  }

  public void setDate(DateTime value) {
    libnfdbJNI.Comment_date_set(swigCPtr, this, DateTime.getCPtr(value), value);
  }

  public DateTime getDate() {
    long cPtr = libnfdbJNI.Comment_date_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DateTime(cPtr, false);
  }

  public void setComment(String value) {
    libnfdbJNI.Comment_comment_set(swigCPtr, this, value);
  }

  public String getComment() {
    return libnfdbJNI.Comment_comment_get(swigCPtr, this);
  }

  public void setAvatar(String value) {
    libnfdbJNI.Comment_avatar_set(swigCPtr, this, value);
  }

  public String getAvatar() {
    return libnfdbJNI.Comment_avatar_get(swigCPtr, this);
  }

  public void setAvatarSize(int value) {
    libnfdbJNI.Comment_avatarSize_set(swigCPtr, this, value);
  }

  public int getAvatarSize() {
    return libnfdbJNI.Comment_avatarSize_get(swigCPtr, this);
  }

  public Comment() {
    this(libnfdbJNI.new_Comment__SWIG_0(), true);
  }

  public Comment(int id, int itemId, String author, String via, DateTime date, String comment, String avatar, int avatarSize) {
    this(libnfdbJNI.new_Comment__SWIG_1(id, itemId, author, via, DateTime.getCPtr(date), date, comment, avatar, avatarSize), true);
  }

  public void Destroy() {
    libnfdbJNI.Comment_Destroy(swigCPtr, this);
  }

}
