/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class GroupPlaceholderController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GroupPlaceholderController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GroupPlaceholderController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_GroupPlaceholderController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GroupPlaceholderController() {
    this(libnfdbJNI.new_GroupPlaceholderController(), true);
  }

  public GroupPlaceholder GetGroupPlaceholderById(int id) {
    return new GroupPlaceholder(libnfdbJNI.GroupPlaceholderController_GetGroupPlaceholderById(swigCPtr, this, id), true);
  }

  public SWIGTYPE_p_std__vectorT_nfdb__GroupPlaceholder_t GetAllGroupPlaceholders() {
    return new SWIGTYPE_p_std__vectorT_nfdb__GroupPlaceholder_t(libnfdbJNI.GroupPlaceholderController_GetAllGroupPlaceholders(swigCPtr, this), true);
  }

  public void AddGroupPlaceholder(GroupPlaceholder groupPlaceholder) {
    libnfdbJNI.GroupPlaceholderController_AddGroupPlaceholder(swigCPtr, this, GroupPlaceholder.getCPtr(groupPlaceholder), groupPlaceholder);
  }

  public void UpdateGroupPlaceholder(GroupPlaceholder groupPlaceholder) {
    libnfdbJNI.GroupPlaceholderController_UpdateGroupPlaceholder(swigCPtr, this, GroupPlaceholder.getCPtr(groupPlaceholder), groupPlaceholder);
  }

  public void RemoveGroupPlaceholder(GroupPlaceholder groupPlaceholder) {
    libnfdbJNI.GroupPlaceholderController_RemoveGroupPlaceholder(swigCPtr, this, GroupPlaceholder.getCPtr(groupPlaceholder), groupPlaceholder);
  }

  public GroupPlaceholder GenerateGroupPlaceholder(SWIGTYPE_p_sql__ResultSet rs) {
    return new GroupPlaceholder(libnfdbJNI.GroupPlaceholderController_GenerateGroupPlaceholder(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs)), true);
  }

}
