/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class ImageController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ImageController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_ImageController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageController() {
    this(libnfdbJNI.new_ImageController(), true);
  }

  public Image GetImageById(int id) {
    long cPtr = libnfdbJNI.ImageController_GetImageById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Image(cPtr, false);
  }

  public imagevector GetImagesByItemId(int itemId) {
    return new imagevector(libnfdbJNI.ImageController_GetImagesByItemId(swigCPtr, this, itemId), true);
  }

  public imagevector GetAllImages() {
    return new imagevector(libnfdbJNI.ImageController_GetAllImages(swigCPtr, this), true);
  }

  public int AddImage(Image image) {
    return libnfdbJNI.ImageController_AddImage(swigCPtr, this, Image.getCPtr(image), image);
  }

  public void UpdateImage(Image image) {
    libnfdbJNI.ImageController_UpdateImage__SWIG_0(swigCPtr, this, Image.getCPtr(image), image);
  }

  public void UpdateImage(int id, SWIGTYPE_p_int itemId, String image, SWIGTYPE_p_int imageSize, SWIGTYPE_p_std__string url) {
    libnfdbJNI.ImageController_UpdateImage__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_int.getCPtr(itemId), image, SWIGTYPE_p_int.getCPtr(imageSize), SWIGTYPE_p_std__string.getCPtr(url));
  }

  public void RemoveImage(int id) {
    libnfdbJNI.ImageController_RemoveImage(swigCPtr, this, id);
  }

  public Image GenerateImage(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.ImageController_GenerateImage(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Image(cPtr, false);
  }

}
