/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class Image {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    libnfdbJNI.Image_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return libnfdbJNI.Image_id_get(swigCPtr, this);
  }

  public void setItemId(int value) {
    libnfdbJNI.Image_itemId_set(swigCPtr, this, value);
  }

  public int getItemId() {
    return libnfdbJNI.Image_itemId_get(swigCPtr, this);
  }

  public void setImage(String value) {
    libnfdbJNI.Image_image_set(swigCPtr, this, value);
  }

  public String getImage() {
    return libnfdbJNI.Image_image_get(swigCPtr, this);
  }

  public void setImageSize(int value) {
    libnfdbJNI.Image_imageSize_set(swigCPtr, this, value);
  }

  public int getImageSize() {
    return libnfdbJNI.Image_imageSize_get(swigCPtr, this);
  }

  public void setUrl(String value) {
    libnfdbJNI.Image_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return libnfdbJNI.Image_url_get(swigCPtr, this);
  }

  public Image() {
    this(libnfdbJNI.new_Image__SWIG_0(), true);
  }

  public Image(int id, int itemId, String image, int imageSize, String url) {
    this(libnfdbJNI.new_Image__SWIG_1(id, itemId, image, imageSize, url), true);
  }

  public void Destroy() {
    libnfdbJNI.Image_Destroy(swigCPtr, this);
  }

}
