/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class imagevector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected imagevector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(imagevector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_imagevector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public imagevector() {
    this(libnfdbJNI.new_imagevector__SWIG_0(), true);
  }

  public imagevector(long n) {
    this(libnfdbJNI.new_imagevector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.imagevector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.imagevector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.imagevector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.imagevector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.imagevector_clear(swigCPtr, this);
  }

  public void add(Image x) {
    libnfdbJNI.imagevector_add(swigCPtr, this, Image.getCPtr(x), x);
  }

  public Image get(int i) {
    long cPtr = libnfdbJNI.imagevector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Image(cPtr, false);
  }

  public void set(int i, Image val) {
    libnfdbJNI.imagevector_set(swigCPtr, this, i, Image.getCPtr(val), val);
  }

}
