/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class layoutvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected layoutvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(layoutvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_layoutvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public layoutvector() {
    this(libnfdbJNI.new_layoutvector__SWIG_0(), true);
  }

  public layoutvector(long n) {
    this(libnfdbJNI.new_layoutvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.layoutvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.layoutvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.layoutvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.layoutvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.layoutvector_clear(swigCPtr, this);
  }

  public void add(Layout x) {
    libnfdbJNI.layoutvector_add(swigCPtr, this, Layout.getCPtr(x), x);
  }

  public Layout get(int i) {
    long cPtr = libnfdbJNI.layoutvector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Layout(cPtr, false);
  }

  public void set(int i, Layout val) {
    libnfdbJNI.layoutvector_set(swigCPtr, this, i, Layout.getCPtr(val), val);
  }

}
