/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class NotificationController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NotificationController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NotificationController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_NotificationController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NotificationController() {
    this(libnfdbJNI.new_NotificationController(), true);
  }

  public Notification GetNotificationById(int id) {
    long cPtr = libnfdbJNI.NotificationController_GetNotificationById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Notification(cPtr, false);
  }

  public notificationvector GetNotificationsBySheetId(int sheetId) {
    return new notificationvector(libnfdbJNI.NotificationController_GetNotificationsBySheetId(swigCPtr, this, sheetId), true);
  }

  public notificationvector GetNotificationsByUsername(String username) {
    return new notificationvector(libnfdbJNI.NotificationController_GetNotificationsByUsername(swigCPtr, this, username), true);
  }

  public notificationvector GetAllNotifications() {
    return new notificationvector(libnfdbJNI.NotificationController_GetAllNotifications(swigCPtr, this), true);
  }

  public int AddNotification(Notification notification) {
    return libnfdbJNI.NotificationController_AddNotification(swigCPtr, this, Notification.getCPtr(notification), notification);
  }

  public void UpdateNotification(Notification notification) {
    libnfdbJNI.NotificationController_UpdateNotification__SWIG_0(swigCPtr, this, Notification.getCPtr(notification), notification);
  }

  public void UpdateNotification(int id, SWIGTYPE_p_std__string username, SWIGTYPE_p_int sheetId) {
    libnfdbJNI.NotificationController_UpdateNotification__SWIG_1(swigCPtr, this, id, SWIGTYPE_p_std__string.getCPtr(username), SWIGTYPE_p_int.getCPtr(sheetId));
  }

  public void RemoveNotification(int id) {
    libnfdbJNI.NotificationController_RemoveNotification(swigCPtr, this, id);
  }

  public void AddFeedUpdateNotifications(int feedid) {
    libnfdbJNI.NotificationController_AddFeedUpdateNotifications(swigCPtr, this, feedid);
  }

  public Notification GenerateNotification(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.NotificationController_GenerateNotification(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new Notification(cPtr, false);
  }

}
