/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class queueitemvector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected queueitemvector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(queueitemvector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_queueitemvector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public queueitemvector() {
    this(libnfdbJNI.new_queueitemvector__SWIG_0(), true);
  }

  public queueitemvector(long n) {
    this(libnfdbJNI.new_queueitemvector__SWIG_1(n), true);
  }

  public long size() {
    return libnfdbJNI.queueitemvector_size(swigCPtr, this);
  }

  public long capacity() {
    return libnfdbJNI.queueitemvector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libnfdbJNI.queueitemvector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libnfdbJNI.queueitemvector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libnfdbJNI.queueitemvector_clear(swigCPtr, this);
  }

  public void add(QueueItem x) {
    libnfdbJNI.queueitemvector_add(swigCPtr, this, QueueItem.getCPtr(x), x);
  }

  public QueueItem get(int i) {
    long cPtr = libnfdbJNI.queueitemvector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new QueueItem(cPtr, false);
  }

  public void set(int i, QueueItem val) {
    libnfdbJNI.queueitemvector_set(swigCPtr, this, i, QueueItem.getCPtr(val), val);
  }

}
