/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nfdb;

public class UserController {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UserController(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libnfdbJNI.delete_UserController(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UserController() {
    this(libnfdbJNI.new_UserController(), true);
  }

  public User GetUserByUsername(String username) {
    long cPtr = libnfdbJNI.UserController_GetUserByUsername(swigCPtr, this, username);
    return (cPtr == 0) ? null : new User(cPtr, false);
  }

  public uservector GetAllUsers() {
    return new uservector(libnfdbJNI.UserController_GetAllUsers(swigCPtr, this), true);
  }

  public int AddUser(User user) {
    return libnfdbJNI.UserController_AddUser(swigCPtr, this, User.getCPtr(user), user);
  }

  public void UpdateUser(User user) {
    libnfdbJNI.UserController_UpdateUser__SWIG_0(swigCPtr, this, User.getCPtr(user), user);
  }

  public void UpdateUser(String username, SWIGTYPE_p_std__string password, String picture, SWIGTYPE_p_int pictureSize, DateTime registered, SWIGTYPE_p_std__string realname, SWIGTYPE_p_std__string email, SWIGTYPE_p_int layout, SWIGTYPE_p_bool admin, SWIGTYPE_p_bool https) {
    libnfdbJNI.UserController_UpdateUser__SWIG_1(swigCPtr, this, username, SWIGTYPE_p_std__string.getCPtr(password), picture, SWIGTYPE_p_int.getCPtr(pictureSize), DateTime.getCPtr(registered), registered, SWIGTYPE_p_std__string.getCPtr(realname), SWIGTYPE_p_std__string.getCPtr(email), SWIGTYPE_p_int.getCPtr(layout), SWIGTYPE_p_bool.getCPtr(admin), SWIGTYPE_p_bool.getCPtr(https));
  }

  public void RemoveUser(String username) {
    libnfdbJNI.UserController_RemoveUser(swigCPtr, this, username);
  }

  public int GetNumberOfUsers() {
    return libnfdbJNI.UserController_GetNumberOfUsers(swigCPtr, this);
  }

  public User GenerateUser(SWIGTYPE_p_sql__ResultSet rs) {
    long cPtr = libnfdbJNI.UserController_GenerateUser(swigCPtr, this, SWIGTYPE_p_sql__ResultSet.getCPtr(rs));
    return (cPtr == 0) ? null : new User(cPtr, false);
  }

}
